-- auto Generated on 2022-10-30
-- DROP TABLE IF EXISTS tug;
CREATE TABLE tug(
    tug_id BIGINT (15) UNIQUE NOT NULL AUTO_INCREMENT COMMENT '拖船id',
    tug_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '拖轮名字',
    tug_code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '拖船代码',
    tug_company_id BIGINT (15) NOT NULL DEFAULT -1 COMMENT '拖轮公司id',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    creat_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创造时间',
    PRIMARY KEY (tug_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'tug';
