-- auto Generated on 2022-10-30
-- DROP TABLE IF EXISTS tug_company;
CREATE TABLE tug_company(
    tug_company_id BIGINT (15) UNIQUE NOT NULL AUTO_INCREMENT COMMENT '名字标识',
    company_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '公司名称',
    company_code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '公司代码',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    creat_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创造时间',
    PRIMARY KEY (tug_company_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'tug_company';
